import { extendTheme, ThemeConfig } from "@chakra-ui/react";
// just generated by boilerplate, you can update it  

const config: ThemeConfig = {
    initialColorMode: "light",
    useSystemColorMode: false,
};

const theme = extendTheme({
    config,
    fonts: {
        body: "'Helvetica Neue LT Std', sans-serif",
        heading: "Iskry, serif",
    },
    fontSizes: {
        xs: "0.75rem",
        sm: "0.875rem", // 14px
        md: "1rem", // default browser: 16px
        lg: "1.125rem", // 18px
        xl: "1.25rem", // 20px
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
        "6xl": "3.75rem",
        "7xl": "4.5rem",
        "8xl": "6rem",
        "9xl": "8rem",
    },
    fontWeights: {
        hairline: 100,
        thin: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
    },
    lineHeights: {
        normal: "normal",
        none: 1,
        shorter: 1.25,
        short: 1.375,
        base: 1.5,
        tall: 1.625,
        taller: "2",
        "3": ".75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
    },
    letterSpacings: {
        tighter: "-0.05em",
        tight: "-0.025em",
        normal: "0",
        wide: "0.025em",
        wider: "0.05em",
        widest: "0.1em",
    },
    colors: {
        gray: {
            50: "#F8F8F8",
            100: "#EDEDED",
            200: "#D9D9D9",
            300: "#C4C4C4",
            400: "#A6A6A6",
            500: "#888888",
            600: "#666666",
            700: "#444444",
            800: "#333333",
            900: "#1F1F1F",
        },
    },
    breakpoints: {
        sm: '30em', // 480px
        md: '48em', // 768px
        lg: '62em', // 992px
        xl: '80em', // 1280px
        '2xl': '96em', // 1536px
        'custom2xl': '1660px', // 1660px
    },
    styles: {
        global: {
            "html, body": {
                bg: "gray.50",
                fontSize: "md",
                color: "gray.800",
            },
            "*::placeholder": {
                color: "gray.400",
            },
            "*::-webkit-scrollbar-track, *::-webkit-scrollbar-thumb": {
                bg: "gray.200",
                borderRadius: "base",
            },
        },
    },
});

export default theme;
